### ISSUE TITLE
API call to create movement

### ISSUE THREAD

**Issue by mlpinit** [ThePops/pandemic#15]
- [ ] `POST "/movements"` with player, from_city and to_city as params

responds with:
- [ ] success / true
- [ ] error message if action is not allowed

---

Note: It should handle dispatcher movements as well

**Comment by smurfik** [comment]
@mlpinit let's check in about the `Note` -- I don't quite get what `handle dispatcher movement` means

**Comment by mlpinit** [comment]
This card wasn't explicit enough. Created other more explicit cards. Closing this.
